//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVW_MultiLanguageImplementation.LanguageResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MVW_MultiLanguageImplementation.LanguageResources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Monitor.
        /// </summary>
        internal static string eizoMain_addMonitor_text {
            get {
                return ResourceManager.GetString("eizoMain_addMonitor_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Preset.
        /// </summary>
        internal static string eizoMain_addPreset_text {
            get {
                return ResourceManager.GetString("eizoMain_addPreset_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add SmartWall.
        /// </summary>
        internal static string eizoMain_addSmartWall_text {
            get {
                return ResourceManager.GetString("eizoMain_addSmartWall_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Monitor.
        /// </summary>
        internal static string eizoMain_editMonitor_text {
            get {
                return ResourceManager.GetString("eizoMain_editMonitor_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Preset.
        /// </summary>
        internal static string eizoMain_editPreset_text {
            get {
                return ResourceManager.GetString("eizoMain_editPreset_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit SmartWall.
        /// </summary>
        internal static string eizoMain_editSmartWall_text {
            get {
                return ResourceManager.GetString("eizoMain_editSmartWall_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor Positions.
        /// </summary>
        internal static string eizoMain_monitorPositions_text {
            get {
                return ResourceManager.GetString("eizoMain_monitorPositions_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Monitor.
        /// </summary>
        internal static string eizoMain_removeMonitor_text {
            get {
                return ResourceManager.GetString("eizoMain_removeMonitor_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Preset.
        /// </summary>
        internal static string eizoMain_removePreset_text {
            get {
                return ResourceManager.GetString("eizoMain_removePreset_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove SmartWall.
        /// </summary>
        internal static string eizoMain_removeSmartWall_text {
            get {
                return ResourceManager.GetString("eizoMain_removeSmartWall_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string general_add {
            get {
                return ResourceManager.GetString("general_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aspect Ratio.
        /// </summary>
        internal static string general_aspectRatio {
            get {
                return ResourceManager.GetString("general_aspectRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string general_cancel {
            get {
                return ResourceManager.GetString("general_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string general_description {
            get {
                return ResourceManager.GetString("general_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deselect.
        /// </summary>
        internal static string general_deselect {
            get {
                return ResourceManager.GetString("general_deselect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string general_edit {
            get {
                return ResourceManager.GetString("general_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP protocol.
        /// </summary>
        internal static string general_HTTPprotocol {
            get {
                return ResourceManager.GetString("general_HTTPprotocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string general_information {
            get {
                return ResourceManager.GetString("general_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP adress.
        /// </summary>
        internal static string general_IpAdress {
            get {
                return ResourceManager.GetString("general_IpAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string general_language {
            get {
                return ResourceManager.GetString("general_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout.
        /// </summary>
        internal static string general_layout {
            get {
                return ResourceManager.GetString("general_layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor.
        /// </summary>
        internal static string general_monitor {
            get {
                return ResourceManager.GetString("general_monitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitors.
        /// </summary>
        internal static string general_monitors {
            get {
                return ResourceManager.GetString("general_monitors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string general_name {
            get {
                return ResourceManager.GetString("general_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Monitor.
        /// </summary>
        internal static string general_newMonitor_text {
            get {
                return ResourceManager.GetString("general_newMonitor_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Preset.
        /// </summary>
        internal static string general_newPreset_text {
            get {
                return ResourceManager.GetString("general_newPreset_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Smart Wall.
        /// </summary>
        internal static string general_newSmartWall_text {
            get {
                return ResourceManager.GetString("general_newSmartWall_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string general_OK {
            get {
                return ResourceManager.GetString("general_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string general_password {
            get {
                return ResourceManager.GetString("general_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset.
        /// </summary>
        internal static string general_preset {
            get {
                return ResourceManager.GetString("general_preset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presets.
        /// </summary>
        internal static string general_presets {
            get {
                return ResourceManager.GetString("general_presets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string general_remove {
            get {
                return ResourceManager.GetString("general_remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string general_save {
            get {
                return ResourceManager.GetString("general_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string general_settings {
            get {
                return ResourceManager.GetString("general_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string general_size {
            get {
                return ResourceManager.GetString("general_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart Wall.
        /// </summary>
        internal static string general_smartWall {
            get {
                return ResourceManager.GetString("general_smartWall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart Walls.
        /// </summary>
        internal static string general_smartWalls {
            get {
                return ResourceManager.GetString("general_smartWalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string general_username {
            get {
                return ResourceManager.GetString("general_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto aligment.
        /// </summary>
        internal static string monitorPosition_autoAligment_text {
            get {
                return ResourceManager.GetString("monitorPosition_autoAligment_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movement.
        /// </summary>
        internal static string monitorPosition_movement_text {
            get {
                return ResourceManager.GetString("monitorPosition_movement_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimensions.
        /// </summary>
        internal static string monitorSettings_dimensions_text {
            get {
                return ResourceManager.GetString("monitorSettings_dimensions_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor information.
        /// </summary>
        internal static string monitorSettings_monitorInformation_text {
            get {
                return ResourceManager.GetString("monitorSettings_monitorInformation_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SmartWall information.
        /// </summary>
        internal static string smartwallSettings_smartwallInformation_text {
            get {
                return ResourceManager.GetString("smartwallSettings_smartwallInformation_text", resourceCulture);
            }
        }
    }
}
